// One-off generator for the module colour themes.
//
// Each theme is built from the SHAPE of the existing lilac/pink ramps — their
// saturation and lightness at every step — with only the hue moved. That is
// what keeps a green module looking like this site rather than like a
// different site: the pastel weight of every step is unchanged.
//
// The two steps used for text and for white-on-colour fills are then darkened
// until they are at least as readable as the lilac they replace, measured, not
// guessed. Yellow and green at lilac's lightness would have been unreadable.

function clamp(n, lo, hi) { return n < lo ? lo : (n > hi ? hi : n); }

function hslToRgb(h, s, l) {
    h = ((h % 360) + 360) % 360; s = s / 100; l = l / 100;
    var c = (1 - Math.abs(2 * l - 1)) * s;
    var x = c * (1 - Math.abs(((h / 60) % 2) - 1));
    var m = l - c / 2, r, g, b;
    if (h < 60)       { r = c; g = x; b = 0; }
    else if (h < 120) { r = x; g = c; b = 0; }
    else if (h < 180) { r = 0; g = c; b = x; }
    else if (h < 240) { r = 0; g = x; b = c; }
    else if (h < 300) { r = x; g = 0; b = c; }
    else              { r = c; g = 0; b = x; }
    return [Math.round((r + m) * 255), Math.round((g + m) * 255), Math.round((b + m) * 255)];
}

function hex(rgb) {
    var s = '#';
    for (var i = 0; i < 3; i++) {
        var h = rgb[i].toString(16).toUpperCase();
        s += h.length === 1 ? '0' + h : h;
    }
    return s;
}

function lin(c) {
    c = c / 255;
    return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
}

function luminance(rgb) {
    return 0.2126 * lin(rgb[0]) + 0.7152 * lin(rgb[1]) + 0.0722 * lin(rgb[2]);
}

/* Contrast against white — the page background, and the text colour laid on
   these when they are used as a fill. */
function contrast(rgb) {
    return 1.05 / (luminance(rgb) + 0.05);
}

/* Darkens until it reads at least as well as the colour it is replacing. */
function toContrast(h, s, l, target) {
    var out = hslToRgb(h, s, l);
    var guard = 0;
    while (contrast(out) < target && l > 8 && guard++ < 90) {
        l -= 1;
        out = hslToRgb(h, s, l);
    }
    return out;
}

/* The shape of the existing ramps: [saturation, lightness] per step. */
var PRIMARY = [
    ['50',  100, 97], ['100', 100, 94], ['200', 84, 88],
    ['400', 69, 77],  ['600', 59, 64],  ['700', 42, 52]
];
var ACCENT = [
    ['50', 100, 97], ['100', 100, 94], ['200', 100, 89],
    ['400', 100, 81], ['600', 82, 67]
];

/* Floors measured off the colours these replace, so no theme is ever harder
   to read than the lilac and pink shipping today.
     lilac-600 #8B6DD9 → 3.98    lilac-700 #6E52B8 → 5.86
     pink-600  #F0669F → 2.95                              */
var FLOOR = { '600': 3.95, '700': 5.80 };
var ACCENT_FLOOR = { '600': 2.90 };

var THEMES = [
    { id: 'navy',     name: 'Dark blue',   ph: 224, ps: 1.00, ah: 196, as: 1.00 },
    { id: 'sky',      name: 'Light blue',  ph: 202, ps: 1.00, ah: 172, as: 0.95 },
    { id: 'forest',   name: 'Dark green',  ph: 154, ps: 0.85, ah: 96,  as: 0.90 },
    { id: 'meadow',   name: 'Light green', ph: 128, ps: 0.85, ah: 78,  as: 0.95 },
    { id: 'maroon',   name: 'Maroon',      ph: 350, ps: 0.80, ah: 20,  as: 0.95 },
    { id: 'coral',    name: 'Light red',   ph: 6,   ps: 1.00, ah: 338, as: 1.00 },
    { id: 'sunshine', name: 'Yellow',      ph: 44,  ps: 1.00, ah: 28,  as: 1.00 },
    { id: 'grape',    name: 'Dark purple', ph: 282, ps: 0.90, ah: 316, as: 0.95 },
    { id: 'lavender', name: 'Light purple',ph: 268, ps: 0.65, ah: 300, as: 0.70 },
    { id: 'rose',     name: 'Pink',        ph: 336, ps: 1.00, ah: 286, as: 0.85 },
    { id: 'ocean',    name: 'Ocean green', ph: 176, ps: 0.90, ah: 202, as: 0.95 },
    { id: 'davy',     name: 'Davy grey',   ph: 262, ps: 0.16, ah: 262, as: 0.22 }
];

var out = [];
function w(s) { out.push(s); }

w('/* Module colour themes — GENERATED by tests/_gentheme.js. Do not hand-edit.');
w('');
w('   Each theme only moves the HUE of the two ramps the whole site is built');
w('   from. Every saturation and lightness step is copied from the lilac and');
w('   pink already in theme.css, which is what keeps a green module looking');
w('   like this site rather than like a different one.');
w('');
w('   The 600 and 700 steps are darkened until they read at least as well as');
w('   the lilac they replace — measured against white, not guessed. Yellow and');
w('   green at lilac\'s own lightness would have been close to invisible.');
w('');
w('   Applied by app.js as a class on <body>, and only while she is inside a');
w('   module. The picker, the schedule and progress span every module at once,');
w('   so they stay the default. */');
w('');

var swatches = [];

for (var t = 0; t < THEMES.length; t++) {
    var th = THEMES[t], i, step, rgb;
    w('body.mtheme-' + th.id + ' {');
    w('  /* ' + th.name + ' */');

    var primary = {};
    for (i = 0; i < PRIMARY.length; i++) {
        step = PRIMARY[i];
        var ps = clamp(step[1] * th.ps, 4, 100);
        rgb = FLOOR[step[0]]
            ? toContrast(th.ph, ps, step[2], FLOOR[step[0]])
            : hslToRgb(th.ph, ps, step[2]);
        primary[step[0]] = rgb;
        w('  --lilac-' + step[0] + ': ' + hex(rgb) + ';');
    }

    var accent = {};
    for (i = 0; i < ACCENT.length; i++) {
        step = ACCENT[i];
        var as = clamp(step[1] * th.as, 4, 100);
        rgb = ACCENT_FLOOR[step[0]]
            ? toContrast(th.ah, as, step[2], ACCENT_FLOOR[step[0]])
            : hslToRgb(th.ah, as, step[2]);
        accent[step[0]] = rgb;
        w('  --pink-' + step[0] + ': ' + hex(rgb) + ';');
    }

    /* Text and rules are tinted toward the module's own hue at the same very
       low saturation the default uses, so the page reads as one colour rather
       than as purple text on a green site. */
    w('  --ink: ' + hex(hslToRgb(th.ph, clamp(25 * th.ps, 6, 100), 27)) + ';');
    w('  --ink-soft: ' + hex(hslToRgb(th.ph, clamp(15 * th.ps, 5, 100), 42)) + ';');
    w('  --muted: ' + hex(hslToRgb(th.ph, clamp(16 * th.ps, 5, 100), 60)) + ';');
    w('  --line: ' + hex(hslToRgb(th.ph, clamp(47 * th.ps, 6, 100), 93)) + ';');
    w('  --bg: ' + hex(hslToRgb(th.ah, clamp(56 * th.as, 6, 100), 98)) + ';');

    /* Shadows are the primary colour at low opacity. Left as lilac they would
       cast a purple glow under a green card. */
    w('  --shadow-rgb: ' + primary['600'][0] + ',' + primary['600'][1] + ',' + primary['600'][2] + ';');

    /* The two extra tints in the background wash. */
    w('  --wash-1: ' + hex(hslToRgb(th.ph + 70, clamp(55 * th.ps, 6, 100), 91)) + ';');
    w('  --wash-2: ' + hex(hslToRgb(th.ph - 55, clamp(65 * th.ps, 6, 100), 94)) + ';');
    w('}');
    w('');

    /* ink / tint / edge are what a calendar chip needs — the strong colour,
       the pale fill and the border between them. accent is for the swatch
       ring in the picker. */
    swatches.push("    { id: '" + th.id + "', name: '" + th.name + "', " +
        "ink: '" + hex(primary['600']) + "', tint: '" + hex(primary['100']) + "', " +
        "edge: '" + hex(primary['200']) + "', accent: '" + hex(accent['400']) + "' }");
}

var fso = new ActiveXObject("Scripting.FileSystemObject");
var repo = fso.GetParentFolderName(fso.GetParentFolderName(WScript.ScriptFullName));

var f = fso.CreateTextFile(repo + "\\public\\css\\modthemes.css", true);
f.Write(out.join('\r\n'));
f.Close();

WScript.Echo('Wrote public/css/modthemes.css — ' + THEMES.length + ' themes.');
WScript.Echo('');
WScript.Echo('Swatch catalogue for themes.js:');
WScript.Echo(swatches.join(',\n'));
WScript.Quit(0);
